version: '3.0'

services:
    gateway:
        container_name: gateway
        env_file:
            - ./apps/gateway/.env
        build:
            context: .
            dockerfile: ./apps/gateway/Dockerfile
            target: production
        ports:
            - 3000:3000
        depends_on:
            - postgres
            - products
            - carts
            - users
        restart: always
    products:
        hostname: products
        container_name: products
        env_file:
            - ./apps/products/.env
        build:
            context: .
            dockerfile: ./apps/products/Dockerfile
            target: production
        ports:
            - 3001
        depends_on:
            - postgres
        restart: always
    carts:
        hostname: carts
        container_name: carts
        env_file:
            - ./apps/carts/.env
        build:
            context: .
            dockerfile: ./apps/carts/Dockerfile
            target: production
        ports:
            - 3002
        depends_on:
            - postgres
        restart: always
    users:
        hostname: users
        container_name: users
        env_file:
            - ./apps/users/.env
        build:
            context: .
            dockerfile: ./apps/users/Dockerfile
            target: production
        ports:
            - 3003
        depends_on:
            - postgres
        restart: always
    orders:
        hostname: orders
        container_name: orders
        env_file:
            - ./apps/orders/.env
        build:
            context: .
            dockerfile: ./apps/orders/Dockerfile
            target: production
        ports:
            - 3004:3004
        depends_on:
            - postgres
        restart: always
    postgres:
        hostname: postgres
        container_name: postgres
        image: postgres:14
        environment:
            - PG_DATA=/var/lib/postgresql/data
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=admin
            - POSTGRES_DB=test
            - POSTGRES_PASSWORD=12345
        ports:
            - 5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always
    redis:
        container_name: redis
        hostname: redis
        image: redis
        ports:
            - 6379
        volumes:
            - redis:/data
volumes:
    pgdata:
    redis:
