version: '3.0'

services:
    gateway:
        container_name: gateway
        env_file:
            - .env.root
            - ./apps/gateway/.env
        build:
            context: .
            dockerfile: ./apps/gateway/Dockerfile
            target: production
        ports:
            - '${GATEWAY_PORT}:${GATEWAY_PORT}'
        depends_on:
            - postgres
            - products
        restart: always
    products:
        hostname: '${PRODUCTS_HOST}'
        container_name: products
        env_file:
            - .env.root
            - ./apps/products/.env
        build:
            context: .
            dockerfile: ./apps/products/Dockerfile
            target: production
        ports:
            - '${PRODUCTS_PORT}:${PRODUCTS_PORT}'
        depends_on:
            - postgres
        restart: always
    carts:
        hostname: '${CARTS_HOST}'
        container_name: carts
        env_file:
            - .env.root
            - ./apps/carts/.env
        build:
            context: .
            dockerfile: ./apps/carts/Dockerfile
            target: production
        ports:
            - '${CARTS_PORT}:${CARTS_PORT}'
        depends_on:
            - postgres
        restart: always
    postgres:
        hostname: '${POSTGRES_HOST}'
        container_name: postgres
        image: postgres:14
        env_file:
            - .env.root
        environment:
            - PG_DATA=/var/lib/postgresql/data
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always

volumes:
    pgdata:
